export enum ActionTypes {
  CONTACT_MODIFIED = '[CONTACT_MODIFIED] Contact Modified',
  CONTACT_NAME_CHANGED = '[CONTACT_MODIFIED] Contact Name Changed',
  CONTACT_EMAIL_CHANGED = '[CONTACT_MODIFIED] Contact Email Changed',
  CONTACT_LINKEDINURL_CHANGED = '[CONTACT_MODIFIED] Contact LinkedIn Url Changed',
  CONTACT_SUBMITED = '[CONTACT_SUBMITED] Contact Submited',
  CONTACT_SUBMITED_SUCCESS = '[CONTACT_SUBMITED] Contact Submited Success',
}
